name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fjtrujy/psp-pkgconf:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base autoconf automake zlib-dev make bash wget cmake git unzip libtool tcl

    - name: Compile Libraries
      run: |
        ./libraries.sh
